author: ynezz
description: "OpenWrt CI native testing"
name: "OpenWrt CI native testing for GitHub Actions"

branding:
  icon: wireless
  color: blue

runs:
  using: 'composite'
  steps:
    - env:
        CI_SOURCE_URL: 'https://gitlab.com/ynezz/openwrt-ci/raw/master'
      run: |
        find $GITHUB_WORKSPACE -type d -exec chmod ugo+w {} \;
        cd $GITHUB_WORKSPACE
        wget -q $CI_SOURCE_URL/Makefile -O Makefile.ci
        make ci-prepare -f Makefile.ci
        docker run --rm --interactive \
          --volume $GITHUB_WORKSPACE:/home/build/openwrt \
          --workdir /home/build/openwrt \
          --env CI_OPENWRT_ROOT=/home/build/openwrt \
          --env CI_ENABLE_UNIT_TESTING \
          --env CI_TARGET_BUILD_DEPENDS \
          --env CI_CMAKE_EXTRA_BUILD_ARGS \
          registry.gitlab.com/ynezz/openwrt-ci/native-testing:latest \
          make ci-native-checks -f Makefile.ci
      shell: bash
